image: golang:1.14.3

stages:
  - lint
  - test
  - build
  - integrationtest

make_lint:
  image: golangci/golangci-lint
  stage: lint
  script:
    - golangci-lint run

unit_tests:
  stage: test
  script:
    - go test -v ./... -coverprofile .testCoverage.txt

client_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/client/service/Dockerfile --destination $CI_REGISTRY_IMAGE/client:$CI_COMMIT_TAG

counter_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/counter/service/Dockerfile --destination $CI_REGISTRY_IMAGE/counter:$CI_COMMIT_TAG

greeter_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/greeter/service/Dockerfile --destination $CI_REGISTRY_IMAGE/greeter:$CI_COMMIT_TAG

logwriter_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/logwriter/service/Dockerfile --destination $CI_REGISTRY_IMAGE/logwriter:$CI_COMMIT_TAG

run_scenario1:
  stage: integrationtest
  image: obraun/golang-micro-ci
  services:
    - name: bitnami/etcd:latest
      alias: etcd
    # - name: nats
    # - name: bitnami/redis:latest
    #   alias: redis
    - name: $CI_REGISTRY_IMAGE/greeter
      alias: greeter
      command: ["--registry_address=etcd:2379 --sleep=30"]
    # - name: $CI_REGISTRY_IMAGE/counter
    #   alias: counter
    #   command: ["--registry_address=etcd:2379", "--broker_address=nats:4222"]
    # - name: $CI_REGISTRY_IMAGE/logwriter
    #   alias: logwriter
    #   command: ["--registry_address=etcd:2379", "--broker_address=nats:4222", "--store_address=redis:6379", "--store_table=sleeper"]
    # - name: $CI_REGISTRY_IMAGE/greeter
    #   alias: greeter
    #   command: ["--registry_address=etcd:2379"]
  variables:
    ALLOW_EMPTY_PASSWORD: "yes"
    ALLOW_NONE_AUTHENTICATION: "yes"
    ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
  script:
    - sleep 60
    - go run client/service/main.go --registry_address=etcd:2379 --store_address=redis:6379  --store_table=sleeper
